import type { ContentDataRecord, AnalysisLog } from './contentReviewTypes';

const createdAt = '2026-08-24T10:00:00+08:00';

export const contentReviewMockRecords: ContentDataRecord[] = [
  {
    id: 'review-demo-xhs-01',
    assetGroupId: 'asset-group-demo-01',
    platformDraftId: 'asset-draft-demo-01-xhs',
    platform: 'xiaohongshu',
    titleSnapshot: '春季轻养护，不靠极端节食',
    publishedAt: '2026-08-21',
    metrics: {
      exposure: '12680',
      coverClickRate: '8.6',
      views: '9240',
      likes: '860',
      favorites: '430',
      comments: '96',
      followersGain: '128',
      interactionRate: '10.9',
      completionRate5s: '72',
    },
    status: 'analyzed',
    createdAt,
  },
  {
    id: 'review-demo-xhs-02',
    assetGroupId: 'asset-group-review-02',
    platform: 'xiaohongshu',
    platformDraftId: 'asset-draft-review-xhs-02',
    titleSnapshot: '久坐人群日常调整建议',
    publishedAt: '2026-08-20',
    metrics: {},
    status: 'pending',
    createdAt,
  },
  {
    id: 'review-demo-douyin-01',
    assetGroupId: 'asset-group-demo-02',
    platformDraftId: 'asset-draft-demo-02-douyin',
    platform: 'douyin',
    titleSnapshot: '家庭聚会中的轻饮场景',
    publishedAt: '2026-08-19',
    metrics: {
      plays: '48600',
      completionRate: '38.5',
      completionRate5s: '76.2',
      likes: '1280',
      comments: '82',
      shares: '146',
      followersGain: '74',
    },
    status: 'entered',
    createdAt,
  },
  {
    id: 'review-demo-video-01',
    assetGroupId: 'asset-group-demo-02',
    platformDraftId: 'asset-draft-demo-02-video',
    platform: 'video-account',
    titleSnapshot: '晚餐前的十分钟，给家人留一点选择',
    publishedAt: '2026-08-18',
    metrics: {
      plays: '19800',
      completionRate: '44.2',
      likes: '520',
      comments: '31',
      shares: '65',
      followersGain: '38',
    },
    status: 'entered',
    createdAt,
  },
  {
    id: 'review-demo-wechat-01',
    assetGroupId: 'asset-group-demo-03',
    platformDraftId: 'asset-draft-demo-03-wechat',
    platform: 'wechat',
    titleSnapshot: '把轻养放回每天的生活节奏',
    publishedAt: '2026-08-17',
    metrics: {
      views: '3150',
      completionRate: '62.8',
      averageReadDuration: '86',
      newFollows: '42',
      shares: '118',
      favorites: '76',
    },
    status: 'entered',
    createdAt,
  },
];

export const contentReviewMockLogs: AnalysisLog[] = [
  {
    id: 'review-log-demo-01',
    platform: 'xiaohongshu',
    scope: 'single',
    recordIds: ['review-demo-xhs-01'],
    dataCount: 1,
    snapshots: [
      {
        recordId: 'review-demo-xhs-01',
        platform: 'xiaohongshu',
        titleSnapshot: '春季轻养护，不靠极端节食',
        publishedAt: '2026-08-21',
        metrics: { exposure: '12680', views: '9240', likes: '860' },
      },
    ],
    report: {
      overview: '这条内容在当前样本中完成了较好的触达和互动，封面点击与收藏表现值得继续复用。',
      strengths: [
        '标题承诺克制，降低了用户的防备感。',
        '早餐后的具体场景让内容更容易被理解和保存。',
      ],
      factors: ['内容与换季生活节点贴合。', '收藏行为高于评论行为，说明内容更偏向参考型。'],
      suggestions: ['继续保留具体时间点和生活场景。', '下一条可以增加一个更清晰的行动步骤。'],
    },
    createdAt: '2026-08-22T09:20:00+08:00',
    status: 'success',
  },
  {
    id: 'review-log-demo-02',
    platform: 'xiaohongshu',
    scope: 'multiple',
    recordIds: ['review-demo-xhs-01', 'review-demo-xhs-02'],
    dataCount: 2,
    snapshots: [
      {
        recordId: 'review-demo-xhs-01',
        platform: 'xiaohongshu',
        titleSnapshot: '春季轻养护，不靠极端节食',
        publishedAt: '2026-08-21',
        metrics: { exposure: '12680', likes: '860' },
      },
      {
        recordId: 'review-demo-xhs-02',
        platform: 'xiaohongshu',
        titleSnapshot: '久坐人群日常调整建议',
        publishedAt: '2026-08-20',
        metrics: {},
      },
    ],
    report: {
      overview: '两条内容的指标完整度不同，当前更适合先比较主题和表达结构，再补充缺失数据。',
      strengths: ['已录入内容的生活场景较清楚。'],
      factors: ['一条内容尚未录入指标，暂时不能进行数值层面对比。'],
      suggestions: ['补齐待录入数据后重新分析。', '保留问题导向标题，减少泛化表达。'],
    },
    createdAt: '2026-08-23T14:30:00+08:00',
    status: 'success',
  },
  {
    id: 'review-log-demo-03',
    platform: 'douyin',
    scope: 'all',
    recordIds: ['review-demo-douyin-01'],
    dataCount: 1,
    snapshots: [
      {
        recordId: 'review-demo-douyin-01',
        platform: 'douyin',
        titleSnapshot: '家庭聚会中的轻饮场景',
        publishedAt: '2026-08-19',
        metrics: { plays: '48600', completionRate: '38.5' },
      },
    ],
    report: {
      overview: '视频完成率处在可继续优化的区间，开头场景和信息进入时机是下一轮重点。',
      strengths: ['家庭餐桌是明确且容易识别的内容场景。'],
      factors: ['前 5 秒需要更快交代观看理由。'],
      suggestions: ['把第一句旁白提前到画面动作出现前。', '继续使用低压力、可模仿的分享动作。'],
    },
    createdAt: '2026-08-24T08:40:00+08:00',
    status: 'success',
  },
];
