import type { TopicItem } from './topicPoolTypes';

export const topicPoolMockItems: TopicItem[] = [
  {
    id: 'topic-demo-0824-01',
    title: '家庭聚会中的轻饮场景',
    type: 'hotspot',
    detail: '从家庭聚会中的轻饮场景切入，观察年轻人如何重新安排一顿饭里的分享和陪伴。',
    reference: '热点雷达：夏末家庭聚餐更偏爱小份、多味的分享方式。',
    status: 'active',
    schedules: [
      {
        id: 'schedule-demo-0825-01',
        date: '2026-08-25',
        channel: '小红书',
        note: '先从家庭餐桌的具体场景写起。',
        titleSnapshot: '家庭聚会中的轻饮场景',
        status: 'pending',
      },
      {
        id: 'schedule-demo-0829-01',
        date: '2026-08-29',
        channel: '视频号',
        note: '补充周末聚会中的低负担选择。',
        titleSnapshot: '家庭聚会中的轻饮场景',
        status: 'pending',
      },
    ],
    contentStatus: 'not-started',
    sourceHotspotId: 'hotspot-0821-03',
  },
  {
    id: 'topic-demo-0824-02',
    title: '把日常营养做成早餐后的固定动作',
    type: 'viral',
    detail: '用一个可复用的早餐后场景，讲清楚轻养产品如何进入真实生活，而不是停留在功能罗列。',
    reference: '澄心健康产品观察：晨间轻养饮的用户访谈摘要。',
    status: 'active',
    schedules: [
      {
        id: 'schedule-demo-0826-01',
        date: '2026-08-26',
        channel: '抖音',
        note: '用连续三天的生活记录做开头。',
        titleSnapshot: '把日常营养做成早餐后的固定动作',
        status: 'pending',
      },
    ],
    contentStatus: 'not-started',
  },
  {
    id: 'topic-viral-analysis-0824-01',
    title: '春季身体状态变化的 3 个常见信号',
    type: 'viral',
    detail: '来自爆款拆解报告的推荐复刻方向，从真实生活场景切入，减少泛泛的专业表达。',
    reference: '爆款分析：https://www.xiaohongshu.com/explore/fictional-spring-care-0824',
    status: 'active',
    schedules: [],
    contentStatus: 'not-started',
  },
  {
    id: 'topic-viral-analysis-0822-01',
    title: '久坐人群每天都能做的 3 个小调整',
    type: 'viral',
    detail: '来自爆款拆解报告的推荐复刻方向，把久坐人群的日常调整拆成简单、可执行的生活动作。',
    reference: '爆款分析：https://www.douyin.com/video/fictional-sedentary-care-0822',
    status: 'active',
    schedules: [],
    contentStatus: 'not-started',
  },
  {
    id: 'topic-demo-0824-03',
    title: '年轻人为什么更愿意为松弛感停留',
    type: 'inspiration',
    detail: '从城市周末和朋友聊天的片段出发，记录健康消费中被重新看见的情绪价值。',
    reference: '团队灵感记录：周末短途出行与慢节奏消费。',
    status: 'active',
    schedules: [],
    contentStatus: 'not-started',
  },
  {
    id: 'topic-demo-0824-04',
    title: '一杯轻养饮如何进入办公室下午三点',
    type: 'viral',
    detail: '把产品使用放回工作日的真实节奏，讨论下午疲惫时人们更容易接受什么样的轻量补给。',
    reference: '澄心健康用户反馈：办公室饮用场景整理。',
    status: 'active',
    schedules: [
      {
        id: 'schedule-demo-0828-01',
        date: '2026-08-28',
        channel: '公众号',
        note: '标题先强调时间点，再落到饮用方式。',
        titleSnapshot: '一杯轻养饮如何进入办公室下午三点',
        status: 'completed',
        contentId: 'content-demo-0828-01',
      },
    ],
    contentStatus: 'completed',
  },
  {
    id: 'topic-demo-0824-05',
    title: '传统配方怎样被讲成听得懂的日常知识',
    type: 'hotspot',
    detail: '从消费者的真实疑问出发，把复杂的配方信息拆成更容易理解的生活判断。',
    reference: '企业资料库：产品配方说明与用户常见问题。',
    status: 'active',
    schedules: [],
    contentStatus: 'not-started',
  },
  {
    id: 'topic-demo-0824-06',
    title: '家庭健康管理不必从复杂计划开始',
    type: 'inspiration',
    detail: '记录家庭成员如何从一个小动作开始建立更可持续的健康管理习惯。',
    reference: '团队灵感记录：家庭健康管理的低门槛动作。',
    status: 'active',
    schedules: [
      {
        id: 'schedule-demo-0830-01',
        date: '2026-08-22',
        channel: '小红书',
        note: '计划日期已过，等待重新安排或进入创作。',
        titleSnapshot: '家庭健康管理不必从复杂计划开始',
        status: 'pending',
      },
    ],
    contentStatus: 'not-started',
  },
  {
    id: 'topic-demo-0824-07',
    title: '夏末晚餐的低负担分享方式',
    type: 'hotspot',
    detail: '从多人分享的小份餐桌切入，梳理夏末家庭晚餐的搭配和交流场景。',
    reference: '热点雷达：夏末家庭聚餐更偏爱小份、多味的分享方式。',
    status: 'archived',
    schedules: [
      {
        id: 'schedule-demo-0822-01',
        date: '2026-08-22',
        channel: '视频号',
        note: '已完成阶段性复盘，暂时归档。',
        titleSnapshot: '夏末晚餐的低负担分享方式',
        status: 'completed',
        contentId: 'content-demo-0822-01',
      },
    ],
    contentStatus: 'completed',
  },
  {
    id: 'topic-demo-0824-08',
    title: '一份适合新手的家庭饮用指南',
    type: 'viral',
    detail: '曾用于早期内容测试，后续不再继续使用。',
    reference: '历史测试记录。',
    status: 'deleted',
    schedules: [],
    contentStatus: 'not-started',
  },
];
